### ISSUE TITLE
Understand why Euro isn't available on some devices

### ISSUE THREAD

**Issue by wbovela** [benoitletondor/EasyBudget#19]
Yeah, totally forgivable of course because it's all so new but just recently Europe introduced the EURO, a unified currency for many of the main European countries. Currencies like the French Frank, the Belgian Frank, the Dutch Guilder and the German Mark haven't been around FOR DECADES!!

**Comment by benoitletondor** [comment]
Hey @wbovela , you realize that if a budget app didn't include the Euro for 9 years you wouldn't be the first one to notice?

The currencies list comes from your device, not the app. So it's still weird that your device doesn't include Euro but let's dig and find out why.

BTW, leaving a bad rating on my app publicly before discussing the problem here is really uncool. I understand you want the app to work but since it's open source, you have the opportunity to make it better, trashing it publicly doesn't help.

**Comment by benoitletondor** [comment]
Now if you're kind enough to remove your comment on the PlayStore, would you also be cool with helping me understand what's going on @wbovela ?

**Comment by benoitletondor** [comment]
Also, since you seems to be a dev too, let me share some code with you. Everything happens here: https://github.com/benoitletondor/EasyBudget/blob/master/Android/EasyBudget/app/src/main/java/com/benoitletondor/easybudgetapp/helper/CurrencyHelper.kt 

As you can see, it uses the `Currency` class from the Android framework.

PS: this kind of attitude from a fellow dev really depresses me...

**Comment by wbovela** [comment]
I'm sure you're very disappointed with a bad review, but the truth is that your application comes with nonsense currencies. There is nothing I can change about that and it is decidedly not my responsibility but yours. 
What depresses me is that developers have the gaul to not only dish out nonsensical functionality, but then blame potential users for their shortcomings. If you KNOW that a platform can show Guilders, Marks and Francs, then take it into account and make sure your app doesn't come off looking as stupid as it does.

Even if your response was valid in any way, there is still nothing I can do about it; it is still your problem. Deal with that.

**Comment by benoitletondor** [comment]
Alright then, thanks a lot for your help 😅
